---
---


In general terms, I do research on animal movement at the University of Toronto, at an amazing lab developing ecological models lead by Prof. Marie-Josee Fortin. I wrote my current independent project, which was succesfully funded by the German research foundation for three years, with the aim of gainning experience on ecological modeling which I had become intrigued by during my PhD while continuing my work on seed dispersal but moving towards more anthopogenized landscapes and animals with larger moving ranges, as I was originally studying small tamarins with moving ranges of 800m. I am at the initial phases of this aim, given covid delays in data sampling, where I explore their movement within the city and how they use the available habitat. For this, I am using movement data of collared coyotes collected by the Ontario Ministry of Forestry and Natural Resources, to understand how cities are permeable through landscape connectivity analysis based on empirical satellite landscape data and a habitat selection function. 

I also have 40 cameras installed in the Toronto region, with support of Prof. Fortin and Prof. Peter Mòlnar and his students, which were initially deployed to validate this first model. Being unspecific data collected by the camera traps, we are using the data beyond validation purposes, to understand the spatio-temporal trends in the presence of large predators, the potential implications of their presence patterns in disease transmission and the effect human activity has on how they use the urban habitats. With these camera traps I also integrated the University of Toronto as an official partner in the Urban Wildlife Information network, which is a cohort of 35 resarch partners across the North American continent, collectively pushing the field of urban ecology forward.

Furthermore, as part of my current project, we have collected over 300 scat specimens across the city. These are being processed and will be used, together with Prof. Mólnar´s lab, for the common goal of understanding not only which seeds are dispersed by wild canines in the city, but also which diseases are being carried by these wild canines and their diet across the urbanization gradient. 

In summary, I am currently using tracking data, camera trap data and scat data, to develop models and understand the spatiotemporal trends in the world of wild canines in the city. What started as a single aim project, became a multi-perspective collaboration with the common goal of understanding the impact and the ecological role of wild canines in mega cities like Toronto, and I am very proud of this because it is all very exciting. Not only to me, but also to the undergraduate and graduate students we are mentoring from data collection to data analysis, creating several projects available for the students of the University of Toronto to participate in.


If you are interested in learning more about urban wildlife in the city of Toronto, I post cool images we find on the camera traps  here, and also share other people´s research and methodological advances in everything related to mammal ecology https://twitter.com/UrbanZoochory.
